### PR TITLE
Porting of some updates from the geonode used branch

### PR DESCRIPTION
**Pull request by mbarto**
With this work we start to align master branch with the 2.1.5 branch used by GeoNode, in particular two commits have been ported:

 - [Align to mapfish print lib 2.1.3-SNAPSHOT](https://github.com/geosolutions-it/mapfish-print/commit/b98ea88321c4668e95831099885c22ddef45f6d6)
 - [Bump to version 2.1.5](https://github.com/geosolutions-it/mapfish-print/commit/96485e183806a307210bb3adbf88d8aca13f4847)

In addition, two dependencies have been upgraded, to align with the version used by GeoServer 2.19.x:
 - JTS to 1.18.1
 - json to 20180813

With this changes:
 - the built print-lib jar works fine in GeoServer 2.19.x
 - the built print-lib jar works fine with MapStore (needs only a quick update to the print applicationContext xml file to include a bunch of new beans)

I have not included other commits from @afabiani that we should look together to understand how they work and eventually test them together:
 - Warp date line support
 - Limit title and legend name
 - Limit to declared scales
 - Tiling WMS Layers

### CODE REVIEW

**Comment by mbarto** [comment]
@afabiani here is the jar to test it in geonode:
[print-lib-geosolutions-2.0-SNAPSHOT.zip](https://github.com/geosolutions-it/mapfish-print/files/8117091/print-lib-geosolutions-2.0-SNAPSHOT.zip)

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
Notes for GeoNode:

 - so far everything works as espected
 - we need to update the `json-20080701.jar` with the one from the official GeoServer WAR, on 2.19.x is `json-20180813.jar`

**Comment by offtherailz** [comment]
Can we change the version of this new update to `geosolutions-2.1.5-SNAPSHOT` or similar. 
We can do a branch of geosolutions-2.0 from the commit before this.

**Comment by mbarto** [comment]
I would go for geosolutions-2.1-SNAPSHOT to mimick what other projects, like geoserver do (not specifying the patch number in snapshots, only major and minor). What do you think @offtherailz @afabiani ?

**Comment by tdipisa** [comment]
> I would go for geosolutions-2.1-SNAPSHOT to mimick what other projects, like geoserver do (not specifying the patch number in snapshots, only major and minor). What do you think @offtherailz @afabiani ?

ok for me @mbarto

**Comment by mbarto** [comment]
@offtherailz version changed, I also pushed a build to the maven repo

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
Great. Please make sure to have it deployed (don't know if there is a dedicated task for it.

**Comment by offtherailz** [comment]
BTW, can you and @tdipisa check a little how to handle changes and versions previous to this?
There is already a geosolutions-2.0.x branch, but on master we have the same name to. I'm wandering the version we are using now, which is deployed and maintained.

The objective of this investigation should be to branch and tag accordingly the version we are using now as geosolutions-2.0-SNAPSHOT and 2.0.x

**Comment by tdipisa** [comment]
The snapshot version on master should be higher than the one on stable branch as usual.

**Pull request merged**
